
//Complete the solution so that it returns a formatted string. The return value should equal "Value is VALUE" where value is a 5 digit padded number. 
function solution(value){
  let arr = value.toString().split('');
  while(arr.length < 5) {
    arr.unshift('0');
  }
  return `Value is ${arr.join('')}`;
}

/*A plant is represented horizontally, from the base to the left, to the end to the right.
The stem is represented by hyphens -, and the flowers are represented by symbols @. A plant always starts with the stem, and always ends with flowers.
Four parameters will be given:
    seed (string) - determines the type of flowers generated by the plant.
    water (integer) - each unit of water extends the portion of stem between the flowers. It also gives how many times the stems + flower clusters should be repeated
    fert (integer) - each unit of fertilizer increases the amount of flowers, grouped in clusters
    temp (integer) - if the temperature given is in the range of 20°C and 30°C, the plant grows normally, otherwise, all the flowers die except for one flower at the end of the stem.
Given the above parameters, your task is to return a string representing the plant. */
function plant(seed, water, fert, temp){
 let arr = new Array(water);
 let stem = '-';
  
  for(let i = 0; i < water; i += 1){
    arr.push(stem.repeat(water));
    arr.push(seed.repeat(fert));
  }
  let result = arr.join('').split('');
  
  if(temp < 20 || temp > 30){
    for(let j = 0; j < result.length; j += 1){
      if(result[j] == seed){
        result.splice(j, 1);
      }
    }
  }  
  return result.join('');
}
